version: '2'
services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/stage_nginx_dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./../frontend_resources/logs:/var/log/nginx